/* Generated by Yosys 0.63 (git sha1 70a11c6bf, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

module voyager_fds(clk, rst_n, mem_we, mem_re, halted, pc_out, mem_rdata, mem_addr, mem_wdata);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  output mem_we;
  wire mem_we;
  output mem_re;
  wire mem_re;
  output halted;
  wire halted;
  output [12:0] pc_out;
  wire [12:0] pc_out;
  input [15:0] mem_rdata;
  wire [15:0] mem_rdata;
  output [12:0] mem_addr;
  wire [12:0] mem_addr;
  output [15:0] mem_wdata;
  wire [15:0] mem_wdata;
  wire S_EXEC;
  wire S_FETCH;
  wire S_HALT;
  wire S_STORE;
  wire ab_59_11;
  wire cat_0;
  wire const_0;
  wire const_12;
  wire cy_59_0;
  wire cy_59_1;
  wire cy_59_10;
  wire cy_59_2;
  wire cy_59_3;
  wire cy_59_5;
  wire cy_59_7;
  wire cy_59_9;
  wire dff_d;
  wire dff_d_0;
  wire dff_d_1;
  wire dff_d_10;
  wire dff_d_11;
  wire dff_d_12;
  wire dff_d_13;
  wire dff_d_14;
  wire dff_d_15;
  wire dff_d_2;
  wire dff_d_3;
  wire dff_d_4;
  wire dff_d_5;
  wire dff_d_6;
  wire dff_d_7;
  wire dff_d_8;
  wire dff_d_9;
  wire pr_0;
  wire pr_1;
  wire pr_10;
  wire pr_11;
  wire pr_12;
  wire pr_2;
  wire pr_3;
  wire pr_4;
  wire pr_5;
  wire pr_6;
  wire pr_7;
  wire pr_8;
  wire pr_9;
  wire xb_59_1;
  wire xb_59_10;
  wire xb_59_11;
  wire xb_59_2;
  wire xb_59_3;
  wire xb_59_4;
  wire xb_59_6;
  wire xb_59_8;
  sky130_fd_sc_hd__dfrtn_1 U20 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(mem_we),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U21 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(mem_re),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U22 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(halted),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U493 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(mem_addr[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U494 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(mem_addr[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U495 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(mem_addr[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U496 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(mem_addr[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U497 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(mem_addr[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U498 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(mem_addr[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U499 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(mem_addr[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__buf_1 U50 (
    .A(pr_0),
    .X(pc_out[0])
  );
  sky130_fd_sc_hd__dfrtn_1 U500 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(mem_addr[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U501 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(mem_addr[8]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U502 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(mem_addr[9]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U503 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(mem_addr[10]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U504 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(mem_addr[11]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U505 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(mem_addr[12]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U506 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(mem_wdata[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U507 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(mem_wdata[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U508 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(mem_wdata[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U509 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(mem_wdata[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__buf_1 U51 (
    .A(pr_1),
    .X(pc_out[1])
  );
  sky130_fd_sc_hd__dfrtn_1 U510 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(mem_wdata[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U511 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(mem_wdata[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U512 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(mem_wdata[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U513 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(mem_wdata[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U514 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(mem_wdata[8]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U515 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(mem_wdata[9]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U516 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(mem_wdata[10]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U517 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(mem_wdata[11]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U518 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(mem_wdata[12]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U519 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(mem_wdata[13]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__buf_1 U52 (
    .A(pr_2),
    .X(pc_out[2])
  );
  sky130_fd_sc_hd__dfrtn_1 U520 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(mem_wdata[14]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U521 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(mem_wdata[15]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__buf_1 U53 (
    .A(pr_3),
    .X(pc_out[3])
  );
  sky130_fd_sc_hd__buf_1 U54 (
    .A(pr_4),
    .X(pc_out[4])
  );
  sky130_fd_sc_hd__buf_1 U55 (
    .A(pr_5),
    .X(pc_out[5])
  );
  sky130_fd_sc_hd__buf_1 U56 (
    .A(pr_6),
    .X(pc_out[6])
  );
  sky130_fd_sc_hd__dfrtn_1 U566 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(pr_0),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U567 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(pr_1),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U568 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(pr_2),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U569 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(pr_3),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__buf_1 U57 (
    .A(pr_7),
    .X(pc_out[7])
  );
  sky130_fd_sc_hd__dfrtn_1 U570 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(pr_4),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U571 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(pr_5),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U572 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(pr_6),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U573 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(pr_7),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U574 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(pr_8),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U575 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(pr_9),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U576 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(pr_10),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U577 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(pr_11),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtn_1 U578 (
    .CLK_N(clk),
    .D(1'h0),
    .Q(pr_12),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__buf_1 U58 (
    .A(pr_8),
    .X(pc_out[8])
  );
  sky130_fd_sc_hd__buf_1 U59 (
    .A(pr_9),
    .X(pc_out[9])
  );
  sky130_fd_sc_hd__buf_1 U60 (
    .A(pr_10),
    .X(pc_out[10])
  );
  sky130_fd_sc_hd__buf_1 U61 (
    .A(pr_11),
    .X(pc_out[11])
  );
  sky130_fd_sc_hd__buf_1 U62 (
    .A(pr_12),
    .X(pc_out[12])
  );
  assign dff_d_12 = 1'h0;
  assign cy_59_2 = 1'h0;
  assign cy_59_10 = 1'h0;
  assign xb_59_11 = 1'h0;
  assign ab_59_11 = 1'h0;
  assign xb_59_3 = 1'h0;
  assign const_0 = 1'h0;
  assign dff_d_11 = 1'h0;
  assign dff_d_10 = 1'h0;
  assign cy_59_3 = 1'h0;
  assign xb_59_4 = 1'h0;
  assign dff_d_9 = 1'h0;
  assign dff_d_8 = 1'h0;
  assign dff_d_7 = 1'h0;
  assign dff_d_6 = 1'h0;
  assign dff_d_5 = 1'h0;
  assign dff_d_4 = 1'h0;
  assign cy_59_5 = 1'h0;
  assign xb_59_6 = 1'h0;
  assign dff_d_3 = 1'h0;
  assign dff_d_2 = 1'h0;
  assign dff_d_1 = 1'h0;
  assign dff_d_0 = 1'h0;
  assign const_12 = 1'h0;
  assign cy_59_0 = 1'h0;
  assign cy_59_7 = 1'h0;
  assign xb_59_8 = 1'h0;
  assign xb_59_1 = 1'h0;
  assign dff_d_15 = 1'h0;
  assign dff_d_14 = 1'h0;
  assign cy_59_1 = 1'h0;
  assign xb_59_2 = 1'h0;
  assign cat_0 = 1'h1;
  assign dff_d = 1'h0;
  assign S_HALT = 1'h1;
  assign S_STORE = 1'h0;
  assign S_EXEC = 1'h1;
  assign S_FETCH = 1'h0;
  assign dff_d_13 = 1'h0;
  assign cy_59_9 = 1'h0;
  assign xb_59_10 = 1'h0;
endmodule
